WINDOW_TITLE_KEYWORD = "燕云十六声"
CAPTURE_BACKEND = "dxcam"
DEBUG = True
LOOP_INTERVAL = 0.12

# 过滤无效窗口
MIN_WINDOW_WIDTH = 100
MIN_WINDOW_HEIGHT = 100

HEALING_THRESHOLD = 0.8
SCREEN_WIDTH = 2560
SCREEN_HEIGHT = 1440